### ISSUE TITLE
How would you support loading indicators for submit buttons?

### ISSUE THREAD

**Issue by alexcroox** [TheAlexLichter/alexander-lichter-repository-fetch#2]
Thank you for taking the time to create the video and this repo!

I use a repository pattern in Nuxt 2 but I'm struggling with Nuxt 3. I want a pattern that allows me to add a loading indicator from $fetch to a submit button, when the API call is executed via a submit function. 

```
const { $api } = useNuxtApp()
const userRepo = repository($api)

function onSubmit(form) {
  userRepo.register(form) // How do I expose the { pending } in the template for a submit button loading state
}
```

**Comment by TheAlexLichter** [comment]
There are various ways. You could create a `state` ref holding the current state (e.g. IDLE, PENDING, SUCCESS, ERROR) and set that via try/catch.

**Comment by alexcroox** [comment]
Thanks, I'm trying to reduce the boilerplate required each time I want to call an API and roll the state into the repository/api service itself. I'll keep hacking away at it, thanks!

**Comment by vicentematus** [comment]
> Thanks, I'm trying to reduce the boilerplate required each time I want to call an API and roll the state into the repository/api service itself. I'll keep hacking away at it, thanks!

In the first place, Thank you Alex for creating educational videos about Nuxt/Vue usage 😸 , it's been reallly helpful.

@alexcroox  @TheAlexLichter  Sorry for reopening this issue, but I'm trying to find a way to reduce boilerplate when doing all this $fetch calls inside functions. I have a lot of patterns repeating the following:


```typescript
const isLoading = ref(false);
const error = ref<Error>();
const users = ref<User>();
async function getUsers() {
  isLoading.value = true;
  try {
    const response = await api.get("/users");
    users.value = response;
  } catch (error) {
    error.value = error as Error;
  } finally {
    isLoading.value = false;
  }
}

```

How did you manage to encapsulate the loading states and errors, using the custom $fetch? I'm trying to encapsulate it for every data fetching, something like this:

```typescript
async function getUsers(){
   const { state, pending, error} = await api.getUsers()
}
```

Isn't the solution for this a straight up composable?

EDIT: It is.
